[package]
name = "zap_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.13.1"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "zap_core_bench"
harness = false